name: Product Overview Page

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build product overview page
        run: npm run build:overview
      
      - name: Run tests
        run: npm test:overview
      
      - name: Deploy to staging
        run: npm run deploy:staging
      
      - name: Approve deployment
        # Add a manual approval step here
        
      - name: Deploy to production
        run: npm run deploy:prod
